import {z} from 'zod'

// NOTE(chloe): This inputSchema is strictly defined in MCP to validate the inputs that can be used in action maps.
// This is not directly used in the current scene graph as this introduces certain incompatibilities with
// xrhome's input-related configurators.
const inputSchema = z.union([
  z.literal('gamepad:button:0').describe('South/A button'),
  z.literal('gamepad:button:1').describe('East/B button'),
  z.literal('gamepad:button:2').describe('West/X button'),
  z.literal('gamepad:button:3').describe('North/Y button'),
  z.literal('gamepad:button:4').describe('Left shoulder button'),
  z.literal('gamepad:button:5').describe('Right shoulder button'),
  z.literal('gamepad:button:6').describe('Left trigger'),
  z.literal('gamepad:button:7').describe('Right trigger'),
  z.literal('gamepad:button:8').describe('Select button'),
  z.literal('gamepad:button:9').describe('Start button'),
  z.literal('gamepad:button:10').describe('Left stick button'),
  z.literal('gamepad:button:11').describe('Right stick button'),
  z.literal('gamepad:button:12').describe('D-pad up'),
  z.literal('gamepad:button:13').describe('D-pad down'),
  z.literal('gamepad:button:14').describe('D-pad left'),
  z.literal('gamepad:button:15').describe('D-pad right'),
  z.literal('gamepad:button:16').describe('Home button'),
  z.literal('gamepad:button:17').describe('Aux button'),
  z.literal('gamepad:axis:left:up').describe('Left joystick up'),
  z.literal('gamepad:axis:left:down').describe('Left joystick down'),
  z.literal('gamepad:axis:left:left').describe('Left joystick left'),
  z.literal('gamepad:axis:left:right').describe('Left joystick right'),
  z.literal('gamepad:axis:right:up').describe('Right joystick up'),
  z.literal('gamepad:axis:right:down').describe('Right joystick down'),
  z.literal('gamepad:axis:right:left').describe('Right joystick left'),
  z.literal('gamepad:axis:right:right').describe('Right joystick right'),

  z.literal('keyboard:KeyA'),
  z.literal('keyboard:KeyB'),
  z.literal('keyboard:KeyC'),
  z.literal('keyboard:KeyD'),
  z.literal('keyboard:KeyE'),
  z.literal('keyboard:KeyF'),
  z.literal('keyboard:KeyG'),
  z.literal('keyboard:KeyH'),
  z.literal('keyboard:KeyI'),
  z.literal('keyboard:KeyJ'),
  z.literal('keyboard:KeyK'),
  z.literal('keyboard:KeyL'),
  z.literal('keyboard:KeyM'),
  z.literal('keyboard:KeyN'),
  z.literal('keyboard:KeyO'),
  z.literal('keyboard:KeyP'),
  z.literal('keyboard:KeyQ'),
  z.literal('keyboard:KeyR'),
  z.literal('keyboard:KeyS'),
  z.literal('keyboard:KeyT'),
  z.literal('keyboard:KeyU'),
  z.literal('keyboard:KeyV'),
  z.literal('keyboard:KeyW'),
  z.literal('keyboard:KeyX'),
  z.literal('keyboard:KeyY'),
  z.literal('keyboard:KeyZ'),
  z.literal('keyboard:Digit0').describe('0 key'),
  z.literal('keyboard:Digit1').describe('1 key'),
  z.literal('keyboard:Digit2').describe('2 key'),
  z.literal('keyboard:Digit3').describe('3 key'),
  z.literal('keyboard:Digit4').describe('4 key'),
  z.literal('keyboard:Digit5').describe('5 key'),
  z.literal('keyboard:Digit6').describe('6 key'),
  z.literal('keyboard:Digit7').describe('7 key'),
  z.literal('keyboard:Digit8').describe('8 key'),
  z.literal('keyboard:Digit9').describe('9 key'),
  z.literal('keyboard:MetaLeft').describe('Left Cmd key'),
  z.literal('keyboard:MetaRight').describe('Right Cmd key'),
  z.literal('keyboard:AltLeft').describe('Left Option key'),
  z.literal('keyboard:AltRight').describe('Right Option key'),
  z.literal('keyboard:ShiftLeft'),
  z.literal('keyboard:ShiftRight'),
  z.literal('keyboard:ControlLeft').describe('Left Ctrl key'),
  z.literal('keyboard:ControlRight').describe('Right Ctrl key'),
  z.literal('keyboard:Minus'),
  z.literal('keyboard:Equal'),
  z.literal('keyboard:BracketLeft'),
  z.literal('keyboard:BracketRight'),
  z.literal('keyboard:Backslash'),
  z.literal('keyboard:Slash'),
  z.literal('keyboard:Semicolon'),
  z.literal('keyboard:Quote').describe('Apostrophe key'),
  z.literal('keyboard:Backquote'),
  z.literal('keyboard:Comma'),
  z.literal('keyboard:Period'),
  z.literal('keyboard:ArrowUp'),
  z.literal('keyboard:ArrowDown'),
  z.literal('keyboard:ArrowLeft'),
  z.literal('keyboard:ArrowRight'),
  z.literal('keyboard:F1'),
  z.literal('keyboard:F2'),
  z.literal('keyboard:F3'),
  z.literal('keyboard:F4'),
  z.literal('keyboard:F5'),
  z.literal('keyboard:F6'),
  z.literal('keyboard:F7'),
  z.literal('keyboard:F8'),
  z.literal('keyboard:F9'),
  z.literal('keyboard:F10'),
  z.literal('keyboard:F11'),
  z.literal('keyboard:F12'),
  z.literal('keyboard:Enter'),
  z.literal('keyboard:Escape'),
  z.literal('keyboard:Backspace'),
  z.literal('keyboard:Tab'),
  z.literal('keyboard:Space'),

  z.literal('mouse:button:0').describe('Left click'),
  z.literal('mouse:button:1').describe('Middle click'),
  z.literal('mouse:button:2').describe('Right click'),
  z.literal('mouse:button:3').describe('Back button'),
  z.literal('mouse:button:4').describe('Forward button'),
  z.literal('mouse:scroll:up'),
  z.literal('mouse:scroll:down'),
  z.literal('mouse:scroll:left'),
  z.literal('mouse:scroll:right'),
  z.literal('mouse:move:up'),
  z.literal('mouse:move:down'),
  z.literal('mouse:move:left'),
  z.literal('mouse:move:right'),

  z.literal('touch').describe('Touch screen input'),
])

// The upsertActionMapsRequestSchema shape matches inputMapSchema. The only difference
// is that it employs a strict inputSchema type for the bindings.
const upsertActionMapsRequestSchema = z.object({
  actionMaps: z
    .record(
      z
        .array(
          z.object({
            name: z.string().describe('Name of the action.'),
            bindings: z.array(
              z.object({
                input: inputSchema,
                modifiers: z
                  .array(inputSchema)
                  .describe(
                    'Additional inputs that must be active concurrently with the primary input to trigger the action (e.g., Ctrl+C, Shift+Click)',
                  ),
              }),
            ),
          }),
        )
        .describe('Array of actions in this action map.'),
    )
    .describe('A record of action maps by their unique names.'),
})

export {upsertActionMapsRequestSchema}
